<?php
/**
 * @file
 * Code for the Movie Catalog Navigation feature.
 */

include_once 'movie_catalog_navigation.features.inc';

/**
 * Implements hook_preprocess_block;
 *
 * @param $variables
 */
function movie_catalog_navigation_preprocess_block(&$variables) {
  if (isset($variables['elements']['#block'])) {
    switch ($variables['elements']['#block']->bid) {
      // Hide the block title.
      case 'system-main-menu' :
      case 'menu-menu-secondary-menu' :
        $variables['elements']['#block']->subject = '';
    }
  }
}
